name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check for merge conflicts
        run: |
          git fetch origin ${{ github.base_ref }}
          if git merge-tree $(git merge-base HEAD origin/${{ github.base_ref }}) HEAD origin/${{ github.base_ref }} | grep -q '<<<<<<<'; then
            echo "Merge conflicts detected"
            exit 1
          fi
      
      - name: Check file sizes
        run: |
          large_files=$(find . -type f -size +1M -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/build/*" -not -path "*/dist/*")
          if [ -n "$large_files" ]; then
            echo "Large files detected:"
            echo "$large_files"
            exit 1
          fi

  coverage-check:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
      redis:
        image: redis:7
        ports:
          - 6379:6379
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          cd backend && npm ci
      
      - name: Run tests with coverage
        run: |
          npm run test:frontend:ci
          cd backend && npm run test:ci
        env:
          NODE_ENV: test
          DATABASE_URL: mongodb://localhost:27017/topsmile_test
          REDIS_URL: redis://localhost:6379
          TEST_JWT_SECRET: test-secret
          TEST_PATIENT_JWT_SECRET: test-patient-secret
      
      - name: Check coverage thresholds
        run: |
          echo "Coverage thresholds checked by Jest configuration"
          echo "Frontend: 70% | Backend: 70%"
